### ISSUE TITLE
怎么用啊！！！

### ISSUE THREAD

**Issue by ghost** [tanrich/cloudMusic#1]
# **_没有什么操作指南吗！？！？_**

**Comment by tanrich** [comment]
@Amonstte 后端API已剥离废除，参考https://binaryify.github.io/NeteaseCloudMusicApi/#/
最新前端代码在本地继续coding中，你可参考现在线上的代码。

# 安装依赖
npm install

# localhost:8080 热加载服务器
npm run dev

# 上线打包
npm run build

# 上线打包分析报告
npm run build --report

**Comment by Amonstte** [comment]
不能下载歌曲的么。。。

**Comment by ghost** [comment]
@422563261 不能下载歌曲的么。。。

**Comment by tanrich** [comment]
@Amonstte 如果你是为了下载歌曲，你直接关注刚刚我发给你的网址就好。我这个现在不附带后端。

**Comment by Amonstte** [comment]
哦。。。、、、谢谢

**Comment by ghost** [comment]
@422563261 哦，谢谢、
